# Generated by Django 2.0.3 on 2018-03-16 19:50

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_artists',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_categories',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_designers',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'designers',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
                ('type', models.CharField(blank=True, choices=[('game', 'game'), ('expansion', 'expansion'), ('accessory', 'accessory'), ('edition', 'edition')], default='game', max_length=24)),
                ('year_published', models.PositiveIntegerField(blank=True, null=True, verbose_name='year published')),
                ('min_players', models.PositiveIntegerField(blank=True, null=True, verbose_name='min players')),
                ('max_players', models.PositiveIntegerField(blank=True, null=True, verbose_name='max players')),
                ('play_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='play time')),
                ('min_play_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='min play time')),
                ('max_play_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='max play time')),
                ('min_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='min age')),
                ('max_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='max age')),
            ],
            options={
                'db_table': 'games',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'games',
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_honors',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'honors',
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_mechanics',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'mechanics',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_publishers',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'publishers',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_subcategories',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_tags',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'tags',
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['id', 'name'], name='game_tags_id_e59de1_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['-created'], name='game_tags_created_ad9a50_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['-modified'], name='game_tags_modifie_056135_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['id', 'name'], name='game_subcat_id_3e95e9_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['-created'], name='game_subcat_created_2410a1_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['-modified'], name='game_subcat_modifie_8d8412_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['id', 'name'], name='game_publis_id_d15fad_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['-created'], name='game_publis_created_ad9ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['-modified'], name='game_publis_modifie_7a0b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanic',
            index=models.Index(fields=['id', 'name'], name='game_mechan_id_740187_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanic',
            index=models.Index(fields=['-created'], name='game_mechan_created_3f4767_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanic',
            index=models.Index(fields=['-modified'], name='game_mechan_modifie_6e9013_idx'),
        ),
        migrations.AddIndex(
            model_name='honor',
            index=models.Index(fields=['id', 'name'], name='game_honors_id_f018c1_idx'),
        ),
        migrations.AddIndex(
            model_name='honor',
            index=models.Index(fields=['-created'], name='game_honors_created_627f48_idx'),
        ),
        migrations.AddIndex(
            model_name='honor',
            index=models.Index(fields=['-modified'], name='game_honors_modifie_8a3a45_idx'),
        ),
        migrations.AddField(
            model_name='game',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Artist', verbose_name='artists'),
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Category', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='game',
            name='designers',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Designer', verbose_name='designers'),
        ),
        migrations.AddField(
            model_name='game',
            name='honors',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Honor', verbose_name='honors'),
        ),
        migrations.AddField(
            model_name='game',
            name='mechanics',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Mechanic', verbose_name='mechanics'),
        ),
        migrations.AddField(
            model_name='game',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='game.Game', verbose_name='game'),
        ),
        migrations.AddField(
            model_name='game',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Publisher', verbose_name='publishers'),
        ),
        migrations.AddField(
            model_name='game',
            name='reimplements',
            field=models.ManyToManyField(blank=True, related_name='reimplemented_by', to='game.Game', verbose_name='reimplements'),
        ),
        migrations.AddField(
            model_name='game',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Subcategory', verbose_name='subcategories'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Tag', verbose_name='tags'),
        ),
        migrations.AddIndex(
            model_name='designer',
            index=models.Index(fields=['id', 'name'], name='game_design_id_f278d4_idx'),
        ),
        migrations.AddIndex(
            model_name='designer',
            index=models.Index(fields=['-created'], name='game_design_created_b52552_idx'),
        ),
        migrations.AddIndex(
            model_name='designer',
            index=models.Index(fields=['-modified'], name='game_design_modifie_7b36ac_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['id', 'name'], name='game_catego_id_b203fe_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-created'], name='game_catego_created_7fcc90_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-modified'], name='game_catego_modifie_36d56a_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['id', 'name'], name='game_artist_id_dd69cd_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['-created'], name='game_artist_created_9d957b_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['-modified'], name='game_artist_modifie_f83f37_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['id', 'name'], name='games_id_dd5471_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-created'], name='games_created_3d643a_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-modified'], name='games_modifie_91a8aa_idx'),
        ),
    ]
