# Generated by Django 2.0.3 on 2018-03-16 17:16

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_categories',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
                ('type', models.CharField(blank=True, choices=[('game', 'game'), ('expansion', 'expansion'), ('accessory', 'accessory'), ('edition', 'edition')], default='game', max_length=24)),
                ('year_published', models.PositiveIntegerField(blank=True, null=True, verbose_name='year published')),
                ('min_players', models.PositiveIntegerField(blank=True, null=True, verbose_name='min players')),
                ('max_players', models.PositiveIntegerField(blank=True, null=True, verbose_name='max players')),
                ('play_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='play time')),
                ('min_play_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='min play time')),
                ('max_play_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='max play time')),
                ('min_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='min age')),
                ('max_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='max age')),
            ],
            options={
                'db_table': 'games',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'games',
            },
        ),
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_mechanisms',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'mechanisms',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_subcategories',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'subcategories',
            },
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['id', 'name'], name='game_subcat_id_3e95e9_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['-created'], name='game_subcat_created_2410a1_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['-modified'], name='game_subcat_modifie_8d8412_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanism',
            index=models.Index(fields=['id', 'name'], name='game_mechan_id_9da407_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanism',
            index=models.Index(fields=['-created'], name='game_mechan_created_29f32b_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanism',
            index=models.Index(fields=['-modified'], name='game_mechan_modifie_d2934f_idx'),
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Category', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='game',
            name='mechanisms',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Mechanism', verbose_name='mechanisms'),
        ),
        migrations.AddField(
            model_name='game',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='game.Game', verbose_name='game'),
        ),
        migrations.AddField(
            model_name='game',
            name='reimplements',
            field=models.ManyToManyField(blank=True, related_name='reimplemented_by', to='game.Game', verbose_name='reimplements'),
        ),
        migrations.AddField(
            model_name='game',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Subcategory', verbose_name='subcategories'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['id', 'name'], name='game_catego_id_b203fe_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-created'], name='game_catego_created_7fcc90_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-modified'], name='game_catego_modifie_36d56a_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['id', 'name'], name='games_id_dd5471_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-created'], name='games_created_3d643a_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-modified'], name='games_modifie_91a8aa_idx'),
        ),
    ]
