# Generated by Django 2.0.3 on 2018-03-16 18:59

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_tags',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'tags',
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['id', 'name'], name='game_tags_id_e59de1_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['-created'], name='game_tags_created_ad9a50_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['-modified'], name='game_tags_modifie_056135_idx'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Tag', verbose_name='tags'),
        ),
    ]
