# Generated by Django 2.0.3 on 2018-03-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(blank=True, choices=[('game', 'game'), ('expansion', 'expansion'), ('accessory', 'accessory'), ('edition', 'edition')], default='game', max_length=24, verbose_name='type'),
        ),
    ]
