# Generated by Django 2.0.3 on 2018-03-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='url'),
        ),
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='url'),
        ),
        migrations.AddField(
            model_name='mechanism',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='url'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='game',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Subcategory', verbose_name='subcategories'),
        ),
    ]
