# Generated by Django 2.0.3 on 2018-03-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180320_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='api_url',
            field=models.URLField(blank=True, null=True, verbose_name='api url'),
        ),
        migrations.AddField(
            model_name='game',
            name='average_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='average rating'),
        ),
        migrations.AddField(
            model_name='game',
            name='complexity',
            field=models.FloatField(blank=True, null=True, verbose_name='complexity'),
        ),
        migrations.AddField(
            model_name='game',
            name='geek_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='geek rating'),
        ),
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='image url'),
        ),
        migrations.AddField(
            model_name='game',
            name='num_votes',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='number of votes'),
        ),
    ]
