# Generated by Django 2.0.3 on 2018-03-16 19:16

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180316_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_artists',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_designers',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'designers',
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_honors',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'honors',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, default='', verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
            ],
            options={
                'db_table': 'game_publishers',
                'ordering': ('name',),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_related_name': 'publishers',
            },
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['id', 'name'], name='game_publis_id_d15fad_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['-created'], name='game_publis_created_ad9ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['-modified'], name='game_publis_modifie_7a0b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='honor',
            index=models.Index(fields=['id', 'name'], name='game_honors_id_f018c1_idx'),
        ),
        migrations.AddIndex(
            model_name='honor',
            index=models.Index(fields=['-created'], name='game_honors_created_627f48_idx'),
        ),
        migrations.AddIndex(
            model_name='honor',
            index=models.Index(fields=['-modified'], name='game_honors_modifie_8a3a45_idx'),
        ),
        migrations.AddIndex(
            model_name='designer',
            index=models.Index(fields=['id', 'name'], name='game_design_id_f278d4_idx'),
        ),
        migrations.AddIndex(
            model_name='designer',
            index=models.Index(fields=['-created'], name='game_design_created_b52552_idx'),
        ),
        migrations.AddIndex(
            model_name='designer',
            index=models.Index(fields=['-modified'], name='game_design_modifie_7b36ac_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['id', 'name'], name='game_artist_id_dd69cd_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['-created'], name='game_artist_created_9d957b_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['-modified'], name='game_artist_modifie_f83f37_idx'),
        ),
    ]
